from __future__ import annotations

from sok_llm_orchestrator.optimization.action_schema import OptimizationAction, validate_optimization_action


def _actions() -> list[OptimizationAction]:
    return [
        OptimizationAction(
            action_id="baseline_control",
            action_family="baseline_control",
            retrieval_policy="metadata",
            corpus_strategy="composition_tight",
            spp_calibration_mode="conservative",
            qlip_guidance_mode="none",
            cell_selection_policy="baseline_default",
            weighting_profile="base_dominant",
            structure_perturbation_profile="minimal",
            template_seed_profile="canonical",
            lattice_candidate_profile="narrow",
            symmetry_relaxation_profile="strict",
            ordering_perturbation_profile="none",
            rationale="Control action that emphasizes baseline comparability.",
            expected_risk_reward={"risk": "low", "reward": "low"},
        ),
        OptimizationAction(
            action_id="guided_hybrid_balanced",
            action_family="guided_exploit",
            retrieval_policy="hybrid",
            corpus_strategy="top_k",
            spp_calibration_mode="balanced",
            qlip_guidance_mode="guidance_only",
            cell_selection_policy="retrieval_informed",
            retrieval_candidate_k=12,
            corpus_top_k=4,
            corpus_strategy_candidates=["top_k", "family_biased"],
            corpus_top_k_candidates=[3, 4, 6],
            spp_package_variant="default",
            spp_package_alternatives=["default", "focus"],
            spp_package_target=0.9,
            spp_payload_profile="balanced",
            spp_guidance_weight=0.6,
            spp_top_k_breakdown=10,
            spp_pairs_policy="task_pairs",
            spp_oob_policy="max",
            spp_missing_pair_policy="max_global",
            weighting_profile="balanced",
            structure_perturbation_profile="moderate",
            template_seed_profile="polymorph_mix",
            lattice_candidate_profile="expanded",
            symmetry_relaxation_profile="soft",
            ordering_perturbation_profile="site_shuffle",
            rationale="Balanced guided action for robust objective improvement attempts.",
            expected_risk_reward={"risk": "medium", "reward": "medium"},
        ),
        OptimizationAction(
            action_id="guided_property_push",
            action_family="guided_exploit",
            retrieval_policy="hybrid",
            corpus_strategy="property_biased",
            spp_calibration_mode="aggressive",
            qlip_guidance_mode="budget_constraint",
            cell_selection_policy="retrieval_informed",
            retrieval_candidate_k=16,
            corpus_top_k=6,
            corpus_strategy_candidates=["property_biased", "top_k", "family_biased"],
            corpus_top_k_candidates=[4, 6, 8],
            spp_package_variant="focus",
            spp_package_alternatives=["focus", "default", "broad"],
            spp_package_target=1.1,
            spp_payload_profile="strong",
            spp_guidance_weight=1.2,
            spp_top_k_breakdown=20,
            spp_pairs_policy="all_available",
            spp_oob_policy="max",
            spp_missing_pair_policy="max_global",
            weighting_profile="property_push_strong",
            structure_perturbation_profile="aggressive",
            template_seed_profile="framework_bias",
            lattice_candidate_profile="multibasin",
            symmetry_relaxation_profile="soft",
            ordering_perturbation_profile="cation_swap_bias",
            rationale="Aggressive guided action for property-biased runs when metadata exists.",
            expected_risk_reward={"risk": "high", "reward": "high"},
        ),
        OptimizationAction(
            action_id="guided_corpus_branch",
            action_family="guided_explore",
            retrieval_policy="hybrid",
            corpus_strategy="family_biased",
            spp_calibration_mode="balanced",
            qlip_guidance_mode="guidance_only",
            cell_selection_policy="retrieval_informed",
            retrieval_candidate_k=20,
            corpus_top_k=8,
            corpus_strategy_candidates=["family_biased", "top_k", "composition_tight"],
            corpus_top_k_candidates=[5, 8, 10],
            spp_package_variant="broad",
            spp_package_alternatives=["broad", "default"],
            spp_package_target=0.8,
            spp_payload_profile="balanced",
            spp_guidance_weight=0.8,
            spp_top_k_breakdown=16,
            spp_pairs_policy="all_available",
            spp_oob_policy="clamp",
            spp_missing_pair_policy="max_global",
            weighting_profile="guidance_dominant",
            structure_perturbation_profile="template_shuffle",
            template_seed_profile="polymorph_mix",
            lattice_candidate_profile="multibasin",
            symmetry_relaxation_profile="relaxed",
            ordering_perturbation_profile="site_shuffle",
            rationale="Explore broader retrieval/corpus branches to escape narrow SPP guidance neighborhoods.",
            expected_risk_reward={"risk": "medium", "reward": "high"},
        ),
        OptimizationAction(
            action_id="guided_payload_probe",
            action_family="guided_explore",
            retrieval_policy="hybrid",
            corpus_strategy="top_k",
            spp_calibration_mode="balanced",
            qlip_guidance_mode="guidance_only",
            cell_selection_policy="retrieval_informed",
            retrieval_candidate_k=12,
            corpus_top_k=4,
            corpus_strategy_candidates=["top_k", "property_biased"],
            corpus_top_k_candidates=[3, 4, 6],
            spp_package_variant="default",
            spp_package_alternatives=["default", "focus"],
            spp_package_target=1.0,
            spp_payload_profile="weak",
            spp_guidance_weight=0.35,
            spp_top_k_breakdown=6,
            spp_pairs_policy="task_pairs",
            spp_oob_policy="clamp",
            spp_missing_pair_policy="zero",
            weighting_profile="base_dominant",
            structure_perturbation_profile="minimal",
            template_seed_profile="canonical",
            lattice_candidate_profile="narrow",
            symmetry_relaxation_profile="strict",
            ordering_perturbation_profile="none",
            rationale="Probe weaker guidance payloads and compare against stronger settings for adaptation decisions.",
            expected_risk_reward={"risk": "low", "reward": "medium"},
        ),
        OptimizationAction(
            action_id="guided_extreme_structure_probe",
            action_family="guided_explore",
            retrieval_policy="hybrid",
            corpus_strategy="family_biased",
            spp_calibration_mode="aggressive",
            qlip_guidance_mode="budget_constraint",
            cell_selection_policy="retrieval_informed",
            retrieval_candidate_k=24,
            corpus_top_k=10,
            corpus_strategy_candidates=["family_biased", "property_biased", "top_k"],
            corpus_top_k_candidates=[6, 8, 10],
            spp_package_variant="broad",
            spp_package_alternatives=["broad", "focus", "default"],
            spp_package_target=1.4,
            spp_payload_profile="strong",
            spp_guidance_weight=1.8,
            spp_top_k_breakdown=28,
            spp_pairs_policy="all_available",
            spp_oob_policy="max",
            spp_missing_pair_policy="max_global",
            weighting_profile="experimental_extreme",
            structure_perturbation_profile="template_shuffle",
            template_seed_profile="ordering_bias",
            lattice_candidate_profile="multibasin",
            symmetry_relaxation_profile="relaxed",
            ordering_perturbation_profile="cation_swap_bias",
            rationale="Escalation probe: strongest bounded guidance plus template perturbation to break structure stagnation.",
            expected_risk_reward={"risk": "high", "reward": "high"},
        ),
        OptimizationAction(
            action_id="retrieval_text_explore",
            action_family="retrieval_explore",
            retrieval_policy="text",
            corpus_strategy="family_biased",
            spp_calibration_mode="balanced",
            qlip_guidance_mode="guidance_only",
            cell_selection_policy="retrieval_informed",
            retrieval_candidate_k=18,
            corpus_top_k=8,
            corpus_strategy_candidates=["family_biased", "top_k"],
            corpus_top_k_candidates=[6, 8],
            spp_package_variant="broad",
            spp_package_alternatives=["broad", "default"],
            spp_package_target=0.85,
            spp_payload_profile="balanced",
            spp_guidance_weight=0.7,
            spp_top_k_breakdown=14,
            spp_pairs_policy="all_available",
            spp_oob_policy="clamp",
            spp_missing_pair_policy="max_global",
            weighting_profile="guidance_dominant",
            structure_perturbation_profile="moderate",
            template_seed_profile="framework_bias",
            lattice_candidate_profile="expanded",
            symmetry_relaxation_profile="soft",
            ordering_perturbation_profile="site_shuffle",
            rationale="Exploration action that broadens retrieved analogues.",
            expected_risk_reward={"risk": "medium", "reward": "medium"},
        ),
        OptimizationAction(
            action_id="retrieval_fingerprint_probe",
            action_family="retrieval_explore",
            retrieval_policy="fingerprint",
            corpus_strategy="top_k",
            spp_calibration_mode="conservative",
            qlip_guidance_mode="guidance_only",
            cell_selection_policy="fixed_benchmark",
            weighting_profile="balanced",
            structure_perturbation_profile="minimal",
            template_seed_profile="canonical",
            lattice_candidate_profile="narrow",
            symmetry_relaxation_profile="strict",
            ordering_perturbation_profile="none",
            rationale="Probe fingerprint neighborhood while controlling candidate cells.",
            expected_risk_reward={"risk": "medium", "reward": "medium"},
        ),
        OptimizationAction(
            action_id="cell_policy_probe",
            action_family="cell_policy",
            retrieval_policy="metadata",
            corpus_strategy="composition_tight",
            spp_calibration_mode="balanced",
            qlip_guidance_mode="guidance_only",
            cell_selection_policy="fixed_benchmark",
            weighting_profile="guidance_dominant",
            structure_perturbation_profile="aggressive",
            template_seed_profile="ordering_bias",
            lattice_candidate_profile="expanded",
            symmetry_relaxation_profile="soft",
            ordering_perturbation_profile="cation_swap_bias",
            rationale="Hold retrieval tight and test cell selection sensitivity.",
            expected_risk_reward={"risk": "low", "reward": "medium"},
        ),
    ]


def list_registered_actions() -> list[OptimizationAction]:
    actions = _actions()
    for action in actions:
        validate_optimization_action(action.to_dict())
    return actions


def legal_action_families() -> list[str]:
    return sorted({action.action_family for action in _actions()})


def get_action(action_id: str) -> OptimizationAction:
    for action in _actions():
        if action.action_id == action_id:
            return action
    raise KeyError(f"Unknown optimization action: {action_id}")


def registry_summary() -> list[dict[str, object]]:
    return [
        {
            "action_id": action.action_id,
            "family": action.action_family,
            "retrieval_policy": action.retrieval_policy,
            "corpus_strategy": action.corpus_strategy,
            "retrieval_candidate_k": action.retrieval_candidate_k,
            "corpus_top_k": action.corpus_top_k,
            "spp_package_variant": action.spp_package_variant,
            "spp_payload_profile": action.spp_payload_profile,
            "weighting_profile": action.weighting_profile,
            "structure_perturbation_profile": action.structure_perturbation_profile,
            "template_seed_profile": action.template_seed_profile,
            "lattice_candidate_profile": action.lattice_candidate_profile,
            "symmetry_relaxation_profile": action.symmetry_relaxation_profile,
            "ordering_perturbation_profile": action.ordering_perturbation_profile,
            "qlip_guidance_mode": action.qlip_guidance_mode,
            "cell_selection_policy": action.cell_selection_policy,
            "risk_reward": action.expected_risk_reward,
        }
        for action in list_registered_actions()
    ]
